server.port=8081
spring.application.name=hb-api-gateway

eureka.client.service-url.defaultZone=http://${EUREKA_SERVER:localhost}:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.healthcheck.enabled=true

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KEYCLOAK_SERVER:localhost}:8080/realms/home-broker/protocol/openid-connect/certs