server.port=8761
spring.application.name=hb-discovery-server

eureka.server.enable-self-preservation=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${EUREKA_SERVER:localhost}:8761/eureka