server.port=0
spring.application.name=hb-auth-service

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false

eureka.client.service-url.defaultZone=http://${EUREKA_SERVER:localhost}:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=false
eureka.client.healthcheck.enabled=true

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

keycloak.url=http://${KEYCLOAK_SERVER:localhost}:8080
keycloak.realm=home-broker
keycloak.client-id=hb-auth-service
keycloak.client-secret=${AUTH_SERVICE_SECRET}

auth.security.api-key=${AUTH_API_KEY}
